const fs = require('fs');
const path = require('path');

const files = {
  'src/lib/config.ts': 'export const DELCOM_BASEURL = process.env.NEXT_PUBLIC_DELCOM_BASEURL || "https://open-api.delcom.org/api/v1";\\nexport const APP_PORT = process.env.APP_PORT || 3000;\\n',
  'src/helpers/apiHelper.ts': 'import { DELCOM_BASEURL } from "@/lib/config";\\n\\nexport const getAccessToken = () => typeof window !== "undefined" ? localStorage.getItem("token") : null;\\nexport const putAccessToken = (token: string) => typeof window !== "undefined" && localStorage.setItem("token", token);\\nexport const removeAccessToken = () => typeof window !== "undefined" && localStorage.removeItem("token");\\n\\nexport const fetchApi = async (endpoint: string, options: RequestInit = {}) => {\\n  const token = getAccessToken();\\n  const headers = new Headers(options.headers || {});\\n  if (token) {\\n    headers.set("Authorization", "Bearer " + token);\\n  }\\n  if (!(options.body instanceof FormData)) {\\n    headers.set("Content-Type", "application/json");\\n  }\\n  \\n  const response = await fetch(DELCOM_BASEURL + endpoint, {\\n    ...options,\\n    headers,\\n  });\\n  const data = await response.json();\\n  if (!response.ok) {\\n    throw new Error(data.message || "Something went wrong");\\n  }\\n  return data;\\n};\\n',
  'src/helpers/toolsHelper.ts': 'import Swal from "sweetalert2";\\n\\nexport const showSuccessDialog = (title: string, text: string) => {\\n  return Swal.fire({ icon: "success", title, text, confirmButtonColor: "#3085d6" });\\n};\\n\\nexport const showErrorDialog = (title: string, text: string) => {\\n  return Swal.fire({ icon: "error", title, text, confirmButtonColor: "#d33" });\\n};\\n\\nexport const showWarningDialog = (title: string, text: string) => {\\n  return Swal.fire({ icon: "warning", title, text, confirmButtonColor: "#f8bb86" });\\n};\\n\\nexport const showConfirmDialog = (title: string, text: string) => {\\n  return Swal.fire({ icon: "question", title, text, showCancelButton: true, confirmButtonColor: "#3085d6", cancelButtonColor: "#d33", confirmButtonText: "Ya", cancelButtonText: "Batal" });\\n};\\n\\nexport const formatDate = (dateString: string) => {\\n  return new Date(dateString).toLocaleDateString("id-ID", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" });\\n};\\n',
  'src/hooks/useInput.ts': 'import { useState, ChangeEvent } from "react";\\n\\nexport const useInput = (initialValue: string) => {\\n  const [value, setValue] = useState(initialValue);\\n  const onChange = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => setValue(e.target.value);\\n  return [value, onChange, setValue] as const;\\n};\\n',
  'src/hooks/redux.ts': 'import { TypedUseSelectorHook, useDispatch, useSelector } from "react-redux";\\nimport type { RootState, AppDispatch } from "@/store";\\n\\nexport const useAppDispatch = () => useDispatch<AppDispatch>();\\nexport const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;\\n',
  'src/types/index.ts': 'export interface User {\\n  id: string;\\n  name: string;\\n  email: string;\\n  avatar: string;\\n}\\n\\nexport interface PostAuthor {\\n  id: string;\\n  name: string;\\n  avatar: string;\\n}\\n\\nexport interface PostComment {\\n  id: string;\\n  body: string;\\n  author: PostAuthor;\\n  createdAt: string;\\n}\\n\\nexport interface Post {\\n  id: string;\\n  body: string;\\n  cover: string | null;\\n  author: PostAuthor;\\n  likes: string[];\\n  comments: PostComment[];\\n  createdAt: string;\\n}\\n\\nexport interface ApiResult<T> {\\n  error: boolean;\\n  message: string;\\n  data: T;\\n}\\n',
  'src/types/action.ts': 'export const ActionType = {\\n  SET_AUTH_USER: "SET_AUTH_USER",\\n  UNSET_AUTH_USER: "UNSET_AUTH_USER",\\n  RECEIVE_USERS: "RECEIVE_USERS",\\n  RECEIVE_POSTS: "RECEIVE_POSTS",\\n  ADD_POST: "ADD_POST",\\n  TOGGLE_LIKE_POST: "TOGGLE_LIKE_POST",\\n  ADD_COMMENT_POST: "ADD_COMMENT_POST",\\n};',
  'src/features/auth/api/authApi.ts': 'import { fetchApi, putAccessToken } from "@/helpers/apiHelper";\\n\\nexport const login = async ({ email, password }: any) => {\\n  const data = await fetchApi("/auth/login", {\\n    method: "POST",\\n    body: JSON.stringify({ email, password }),\\n  });\\n  putAccessToken(data.data.token);\\n  return data;\\n};\\n\\nexport const register = async ({ name, email, password }: any) => {\\n  return await fetchApi("/auth/register", {\\n    method: "POST",\\n    body: JSON.stringify({ name, email, password }),\\n  });\\n};\\n',
  'src/features/users/api/userApi.ts': 'import { fetchApi } from "@/helpers/apiHelper";\\n\\nexport const getAllUsers = async () => fetchApi("/users");\\nexport const getProfile = async () => fetchApi("/users/me");\\nexport const updateProfile = async (body: any) => fetchApi("/users/me", { method: "PUT", body: JSON.stringify(body) });\\nexport const updateProfilePhoto = async (formData: FormData) => fetchApi("/users/me/photo", { method: "POST", body: formData });\\nexport const updatePassword = async (body: any) => fetchApi("/users/me/password", { method: "PUT", body: JSON.stringify(body) });\\n',
  'src/features/posts/api/postApi.ts': 'import { fetchApi } from "@/helpers/apiHelper";\\n\\nexport const getPosts = async (isMe = 0) => fetchApi("/posts?is_me=" + isMe);\\nexport const getPostDetail = async (id: string) => fetchApi("/posts/" + id);\\nexport const addPost = async (body: any) => fetchApi("/posts", { method: "POST", body: JSON.stringify(body) });\\nexport const updatePost = async (id: string, body: any) => fetchApi("/posts/" + id, { method: "PUT", body: JSON.stringify(body) });\\nexport const updatePostCover = async (id: string, formData: FormData) => fetchApi("/posts/" + id + "/cover", { method: "POST", body: formData });\\nexport const deletePost = async (id: string) => fetchApi("/posts/" + id, { method: "DELETE" });\\nexport const toggleLike = async (id: string) => fetchApi("/posts/" + id + "/likes", { method: "POST" });\\nexport const addComment = async (id: string, body: any) => fetchApi("/posts/" + id + "/comments", { method: "POST", body: JSON.stringify(body) });\\nexport const deleteComment = async (id: string, commentId: string) => fetchApi("/posts/" + id + "/comments/" + commentId, { method: "DELETE" });\\n',
  'src/store.ts': 'import { configureStore } from "@reduxjs/toolkit";\\nimport authReducer from "@/features/auth/states/reducer";\\nimport usersReducer from "@/features/users/states/reducer";\\nimport postsReducer from "@/features/posts/states/reducer";\\n\\nexport const store = configureStore({\\n  reducer: {\\n    auth: authReducer,\\n    users: usersReducer,\\n    posts: postsReducer,\\n  },\\n});\\n\\nexport type RootState = ReturnType<typeof store.getState>;\\nexport type AppDispatch = typeof store.dispatch;\\n',
  'src/components/Providers.tsx': '\\"use client\\";\\nimport { Provider } from "react-redux";\\nimport { store } from "@/store";\\n\\nexport default function Providers({ children }: { children: React.ReactNode }) {\\n  return <Provider store={store}>{children}</Provider>;\\n}\\n',
  'src/app/layout.tsx': 'import type { Metadata } from "next";\\nimport { Inter } from "next/font/google";\\nimport "./globals.css";\\nimport Providers from "@/components/Providers";\\n\\nconst inter = Inter({ subsets: ["latin"] });\\n\\nexport const metadata: Metadata = {\\n  title: "Delcom Posts",\\n  description: "Aplikasi Manajemen Postingan",\\n};\\n\\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\\n  return (\\n    <html lang="id">\\n      <body className={inter.className}>\\n        <Providers>{children}</Providers>\\n      </body>\\n    </html>\\n  );\\n}\\n'
};

Object.entries(files).forEach(([filepath, content]) => {
  const fullPath = path.resolve(process.cwd(), filepath);
  fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  fs.writeFileSync(fullPath, content);
  console.log('Created ' + filepath);
});
