export const ActionType = {
  SET_AUTH_USER: "SET_AUTH_USER",
  UNSET_AUTH_USER: "UNSET_AUTH_USER",
  RECEIVE_USERS: "RECEIVE_USERS",
  RECEIVE_POSTS: "RECEIVE_POSTS",
  ADD_POST: "ADD_POST",
  TOGGLE_LIKE_POST: "TOGGLE_LIKE_POST",
  ADD_COMMENT_POST: "ADD_COMMENT_POST",
};